version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-php-algoritmos

  nginx:
    image: nginx:latest
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php-algoritmos
  
networks:
  app-php-algoritmos:
    driver: bridge